version: '3'
services:
    app:
        container_name: moist_server
        restart: always
        build: ./moisture_serve
        ports:
            - '80:8081'
        links:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - "27017:27017"
